#

services:
  apache:
    build: 
      context: ./laravel
      dockerfile: apache.dockerfile
    ports:
      - "80:80"
    volumes:
      - ./laravel:/var/www/html
    restart: always
    networks:
      - appnet

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apiDataBase
      MYSQL_USER: ale
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - appnet

  
  react:
    build: 
      context: ./react
      dockerfile: react.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./react:/app
    restart: always
    networks:
      - appnet

networks:
  appnet:

volumes:
  mariadb_data: