
services:
  apache:
    build: 
      context: ./laravel
      dockerfile: apache.dockerfile
    ports:
      - "80:80"
    volumes:
      - ./laravel:/var/www/html
    restart: always
    networks:
      - backend
      - frontend

  maraiadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apiDataBase
      MYSQL_USER: ale
      MYSQL_PASSWORD: password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend

  
  react:
    build: 
      context: ./react
      dockerfile: react.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./react:/app
    restart: always
    networks:
      - frontend

networks:
  backend:
  frontend:

volumes:
  mariadb_data: